/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Tutorial: Bootstrap Accordion (final), at
* https://www.jitblox.com/project/4tvhtDS4Av/tutorial-bootstrap-accordion-final
*/

/**
* Represents a Game of Thrones character.
*/
export interface Character {
  /**
  * The name of the character.
  */
  name?: string;
  /**
  * A short introduction of the character.
  */
  about?: string;
  /**
  * The actor playing the character.
  */
  actor?: string;
  /**
  * An URL of the character's photo.
  */
  photoUrl?: string;
}
