/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Tutorial: Bootstrap Accordion (final), at
* https://www.jitblox.com/project/4tvhtDS4Av/tutorial-bootstrap-accordion-final
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { NgbAccordionModule } from '@ng-bootstrap/ng-bootstrap';
import { Character } from '../../model';
import { CharacterDetailComponent } from './character-detail.component';

/**
* This page displays a dynamic list of Game of Thrones characters and reveals the character details
* when clicking the a "Details" link.
*/
@Component({
  selector: 'app-characters-page',
  standalone: true,
  templateUrl: './characters-page.component.html',
  imports: [NgbAccordionModule, CharacterDetailComponent, CommonModule]
})
export class CharactersPageComponent {
  /**
  * Contains a list of Game of Thrones characters.
  */
  public characters: Character[] = [
    {
      name: 'Eddard "Ned" Stark',
      about: 'Ned is the lord of Winterfell, an ancient fortress in the North of the fictional continent of Westeros. Though the character is established as the main character in the novel and the first season of the TV adaptation, a plot twist involving Ned near the end of the novel and the end of the first season shocked both readers of the book and viewers of the TV series',
      actor: 'Sean Bean',
      photoUrl: 'https://media.jitblox.com/tutorials/bootstrap-accordion/ned-stark.jpg'
    },
    {
      name: 'Robert Baratheon',
      about: 'Introduced in 1996\'s A Game of Thrones, Robert is the eldest son and heir of Lord Steffon Baratheon. He is a close friend to Ned Stark, both being wards of Lord Jon Arryn. After his betrothed Lyanna Stark was allegedly kidnapped by prince Rhaegar Targaryen, Robert, Ned and Jon started a rebellion against the "Mad King" Aerys II Targaryen. After crushing the Targaryen dynasty and winning the war, during which Lyanna died, Robert took the Iron Throne.',
      actor: 'Mark Addy',
      photoUrl: 'https://media.jitblox.com/tutorials/bootstrap-accordion/robert-baratheon.jpg'
    },
    {
      name: 'Jaime Lannister',
      about: 'Jaime is a knight of the Kingsguard and one of the best swordsmen in the seven kingdoms. He is a member of House Lannister, the wealthiest and one of the most powerful families in the kingdom of Westeros. He is the elder son of Tywin Lannister, twin brother of Cersei, with whom he has a longstanding incestuous relationship, and brother of Tyrion. Although Jaime first appears to be unscrupulous and immoral, he later proves to be more complex, honorable, and sympathetic. His lengthy character development has been praised by critics of the novels and the television show.',
      actor: 'Nikolaj Coster-Waldau',
      photoUrl: 'https://media.jitblox.com/tutorials/bootstrap-accordion/jaime-lannister.jpg'
    },
    {
      name: 'Catelyn Stark',
      about: 'Catelyn Stark is described as beautiful, with fair skin, long auburn hair, blue eyes, long fingers, high cheekbones and full breasts, and dressed simply in the grey color of House Stark or the blue and red of her father’s House Tully. She is proud, strong, kind and generous, has a strong grasp of politics, and is often governed by the desire to protect her children. Catelyn is usually in accord with her husband Eddard Stark, but resents his admission of his extramarital son Jon Snow into their household.',
      actor: 'Michelle Fairley',
      photoUrl: 'https://media.jitblox.com/tutorials/bootstrap-accordion/catelyn-stark.png'
    },
    {
      name: 'Cersei Lannister',
      about: 'Cersei is Queen of the Seven Kingdoms of Westeros by marriage to King Robert Baratheon, who abuses her throughout their marriage. Her father, Tywin, arranged the marriage after his attempt to betroth her to Prince Rhaegar Targaryen, whom she idolized as a child, failed. Robert took the Throne with the help of the Lannisters when he ended the Targaryen dynasty. Cersei has been involved in an incestuous affair with her twin brother, Jaime, since childhood. All three of Cersei\'s children are Jaime\'s, which is unbeknownst to Robert. The rumored illegitimacy of her children causes a power struggle in the wake of the king\'s death, known as the War of Five Kings.',
      actor: 'Lena Headey',
      photoUrl: 'https://media.jitblox.com/tutorials/bootstrap-accordion/cersei-lannister.jpg'
    }
  ];

  /**
  * The character that is currently selected for display in the detail view.
  */
  public selectedCharacter?: Character;

  constructor() {}

  public onHyperlink1Click($event: MouseEvent, charactersItem: Character): void {
    this.selectedCharacter = charactersItem;
    $event.preventDefault();
  }
}
