/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Tutorial: Bootstrap Accordion (final), at
* https://www.jitblox.com/project/4tvhtDS4Av/tutorial-bootstrap-accordion-final
*/

import { Routes } from '@angular/router';
import { CharactersPageComponent } from './components/Characters/characters-page.component';
import { HomeComponent } from './components/Home/home.component';

export const routes: Routes = [
  {
    path: 'characters-page',
    component: CharactersPageComponent
  },
  {
    path: 'home',
    component: HomeComponent
  },
  {
    path: '',
    redirectTo: '/characters-page',
    pathMatch: 'full'
  }
];
